### PR TITLE
`Is250Bits` hint

### LINKED ISSUE #569: `Is250Bits` hint
https://github.com/starkware-libs/cairo-lang/blob/0e4dab8a6065d80d1c726394f5d9d23cb451706a/src/starkware/starknet/common/storage.cairo#L24C12-L24C55

https://github.com/lambdaclass/cairo-vm/blob/db7fff18c9c1312024ebf4119fcdfeba23657b12/vm/src/hint_processor/builtin_hint_processor/hint_code.rs#L101

https://github.com/starkware-libs/cairo-lang/blob/0e4dab8a6065d80d1c726394f5d9d23cb451706a/src/starkware/starknet/security/whitelists/0.10.3.json#L642

### PR DESCRIPTION
**Pull request by diegoTech14**
Resolves #569

### CODE REVIEW

**Comment by diegoTech14** [comment]
Hey @TAdev0, have I written the hint code in the correct part of the file? 

Also, I'm trying to add the case but I don't know what category is this issue...
let me know, please.

**Comment by diegoTech14** [comment]
Thank you sir @MaksymMalicki I've seen failing "Golangci Linting" check but I don't know why, could you bring me more info please?

**Comment by diegoTech14** [comment]
Thank you sir @MaksymMalicki I've seen failing "Golangci Linting" check but I don't know why, could you bring me more info please?

**Comment by MaksymMalicki** [comment]
> Thank you sir @MaksymMalicki I've seen failing "Golangci Linting" check but I don't know why, could you tell me what's happening please?

You just need to run `golangci-lint run` and commit the changes. Your project is not linted. I hope this helps 🫡

**Comment by diegoTech14** [comment]
Oh, thank you sir, I will do that! 😃

**Comment by diegoTech14** [comment]
Hi! I've closed this because I would like to create a new draft PR

**Pull request closed without merging**
