### PR TITLE
Separate bench cmd

### LINKED ISSUE #526: feat: create a separate command to run benchmarks
Currently, benchmarks are run each time we do `make integration` . This lead to the txt file being overwritten again and again.

### PR DESCRIPTION
**Pull request by fmmesen**
Resolves #526 

Changes made:
Removed the code that created the Benchmarks.txt file when the make integration command is run.
Added a new command `make integrationbench` that creates the Benchmarks.txt file with performance data.

Detailed description:
Command `make integration`: Now only runs the integration tests without generating the Benchmarks.txt file.
Command `make integrationbench`: This new command runs only the benchmark tests and generates the Benchmarks.txt file, providing detailed performance information.

### CODE REVIEW

**Comment by TAdev0** [comment]
hey @fmmesen , thanks for your PR. Could you also modify the readme file to explain how to run benchmarks to compare performances with the python VM  on cairo zero files ?

 there any way to avoid the huge code duplicate that your proposed solution implies?

**Comment by TAdev0** [comment]
hey @fmmesen 

@har777  proposed a more efficient solution to avoid code duplication.
Lets create a `make zerobench` command (because we already have a `make bench` command for something else)

Then you just keep only one benchmarks file, and do something like : 

```
import (
	"flag"
	"testing"
)

var zerobench = flag.Bool("zerobench", false, "run Integration tests and generates benchmarks file")

func TestCairoZeroFilesWithBenchmarks(t *testing.T) {
	// Your test code here
	// ...

	if zerobench {
		wrap the WriteToBenchmark line in it
	}
}
```

**Comment by fmmesen** [comment]
Hello @TAdev0 !
Ok, I'll check it tonight

**Comment by fmmesen** [comment]
Sorry @TAdev0 seems that I made a mistake working with github, but there's a new PR #597

**Pull request closed without merging**
