### PR TITLE
Move WriteUint256ToAddress and WriteToNthStructField to memory package

### PR DESCRIPTION
**Pull request by EmmanuelAR**
- Move WriteUint256ToAddress from hinter package to memory package
-  Move WriteToNthStructField from hinter package to memory package
- IMPORTANT NOTE:  I know that i dont have to move WriteToNthStructField but if i want to migrate the WriteUint256ToAddress  i have to move WriteToNthStructField too, because inside in the WriteUint256ToAddress i have to call WriteToNthStructField ).
- Fix the calls in the source code  for the two functions (WriteUint256ToAddress, WriteToNthStructField )

Project build sucess:
image
Test run sucess:
image

### CODE REVIEW

**Comment by EmmanuelAR** [comment]
Also i fix this link in the readme file 

Screenshot 2024-05-23 232742

Pass link
image

NEW LINK

**Review by TAdev0 — APPROVED** [review]
lgtm!

**Comment by TAdev0** [comment]
@EmmanuelAR  you just have a linting issue in the memory.go file, can you address this?

**Comment by EmmanuelAR** [comment]
Sure @TAdev0, let me check!!

**Comment by EmmanuelAR** [comment]
Hey @TAdev0
Heres the commit to fix the format in memory.go file 
Commit: https://github.com/NethermindEth/cairo-vm-go/pull/428/commits/b6a59082c65fd34c0e85164694e4b5376b945f2f

**Comment by TAdev0** [comment]
thanks!

**Comment by TAdev0** [comment]
Closes #426 
Closes #427

**Pull request merged**
