### PR TITLE
`Uint256` hints integration tests

### PR DESCRIPTION
**Pull request by Sh0g0-1758**
This is not ready to merge right now. 
The cairo integration tests are detected because I have modified the `cairozero_test.go` file.

This PR is aims to do the tasks mentioned here : #413 

Current Progress : 

- [x]  Uint256Add
- [x]  Uint256AddLow
- [x]  Split64
- [x]  Uint256Sqrt
- [x]  Uint256SignedNN
- [x]  Uint256UnsignedDivRem
- [x]  Uint256MulDivMod

### CODE REVIEW

**Comment by TAdev0** [comment]
@Sh0g0-1758  why is Split64 in Uint256? It works on a field element in the range [0, 2^192), splitting in in its low 64-bit and high 128-bit parts

**Comment by TAdev0** [comment]
hey @Sh0g0-1758  how is it going with this?

**Comment by Sh0g0-1758** [comment]
Ran into a roadblock yesterday. Resolved it and will hopefully have this ready by EOD.

**Comment by Sh0g0-1758** [comment]
Closing this as this was not forked from finalize segments.

**Pull request closed without merging**
